openapi: 3.0.3
info:
  title: ReviewDataLayer
  description: Data Layer managing internal storage for reviews.
  version: 1.0.0
servers:
  - url: https://review-dl/api/v1


paths:
  /:
    get:
      summary: Get reviews
      description: Get the reviews for the specified sitting spot
      operationId: getReviews
      parameters:
        - name: reviewId
          in: query
          description: unique id of the sitting spot
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Reviews found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewResult'
                
        400:
          description: Invalid input
          

    post:
      summary: Post a new review
      description: create a new review for an existing sitting spot
      operationId: postReview
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      responses:
        201:
          description: Review entry created
          content:
            application/json:
              schema:
                type: string
                format: uuid
        400:
          description: Invalid input



components:
  schemas:
  
    Review:
      description: corpus of the review
      properties:
        corpus:
          type: string
          
    ReviewResult:
      description: list of reviews
      properties:
        id:
          type: string
          format: uuid
        result:
          type: array
          items:
            type: string
